### ISSUE TITLE
Documentation work division

### ISSUE THREAD

**Issue by YixinZhang92** [Regional-Geop-Synthesis/Magnetic_Gravity_Data_Process#1]
Hi, all. I would like to do the documentation of the plot directory. 

If anyone else has already started on it please let me know.

@elizabethgilmour @luh1202 @gengyu89

**Comment by gengyu89** [comment]
Hi, all

@YixinZhang92 @elizabethgilmour @luh1202 @capowell2 

My previous two packages were uploaded to a temporary repository, both with very detailed documentations. The GitHub version will keep up-to-date. Please always use the GitHub version when you need them.

https://github.com/gengyu89/Homework4_Comp_Methods/tree/master/redist_cen_maggrav_yugeng
https://github.com/gengyu89/Homework4_Comp_Methods/tree/master/redist_prob2_gravmod_yugeng

I will continue making changes until the end of the semester. Then, I will push the final version onto the public repository.

**Comment by gengyu89** [comment]
Hi, all

@ChunyuMemphis @luh1202 @elizabethgilmour @YixinZhang92 

Please arrange the directories by their functionalities except for the markdown files. A suggested setting could be like:
    - forward_modeling_grav2d_by_chuck/
    - inverse_modeling_prob2_by_shuchioung/
    - detrend_continuation_derivative_by_chunyu/
    - data_sources.md
    - README.md

Avoid uploading files in the root directory. The current setting looks like a mess.

Cheers

**Comment by YixinZhang92** [comment]
Done.
